openapi: 3.0.0
info:
  title: Example API
  description: This is an example API
  version: 1.0.0
servers:
  - url: http://localhost:8080/
paths:
  /register:
    post:
      summary: Register
      description: Register a new user
      requestBody:
        description: JSON object with the user data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email address
                username:
                  type: string
                  description: The username
                password:
                  type: string
                  description: The password
      responses:
        "201":
          description: JSON object with the user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message of successful registration
                  token:
                    type: string
                    description: The generated JWT token for further authentication
                  role:
                    type: string
                    description: The role of the user
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /login:
    post:
      summary: Login
      description: Login a user
      requestBody:
        description: JSON object with the user data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email address
                username:
                  type: string
                  description: The username
                password:
                  type: string
                  description: The password
      responses:
        "200":
          description: JSON object with the user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The generated JWT token for further authentication
                  role:
                    type: string
                    description: The role of the user
        "401":
          description: JSON object with the error message due to unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /user:
    post:
      summary: Check user's eligibility based on the JWT token
      description: Check user's eligibility based on the JWT token
      requestBody:
        description: JSON object with the user data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: The JWT token provided by the user
      responses:
        "200":
          description: JSON object with the user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  hasRemainingQuota:
                    type: boolean
                    description: Boolean indicating if the user has remaining quota to use the backend API
                  newToken:
                    type: string
                    description: The new JWT token for authentication
        "401":
          description: JSON object with the error message due to unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message                
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /role:
    post:
      summary: Check user's role based on the JWT token
      description: Check user's role based on the JWT token
      requestBody:
        description: JSON object with the user data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: The JWT token provided by the client
      responses:
        "200":
          description: JSON object with the user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  role:
                    type: string
                    description: The role of the user
                  newToken:
                    type: string
                    description: The new JWT token for authentication
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /record:
    post:
      summary: Record the usage of API services
      description: Record the usage of API services
      requestBody:
        description: JSON object with the user data
        required: true
        content:
          application/json:
            schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The JWT token of user
                  endpoint:
                    type: string
                    description: The endpoint of the API
                    example: /news
                  method:
                    type: string
                    description: The method of the API
                    example: POST
                  timestamp:
                    type: number
                    description: The timestamp of the API call in epoch time
                    example: 1701216146000
      responses:
        "201":
          description: JSON object with the success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message of successful recording
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /bookmark-words/{userID}:
    get:
      summary: Get bookmarked words
      description: Get bookmarked words
      parameters:
        - name: userID
          in: path
          description: The user ID
          required: true
          schema:
            type: number
            example: 1
      responses:
        "200":
          description: JSON object with the bookmarked words
          content:
            application/json:
              schema:
                type: object
                properties:
                  words:
                    type: array
                    items:
                      type: string
                    description: The bookmarked words
        "401":
          description: JSON object with the error message due to unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message   
    post:
      summary: Add bookmarked words
      description: Add bookmarked words
      parameters:
        - name: userID
          in: path
          description: The user ID
          required: true
          schema:
            type: number
            example: 1
      requestBody:
        description: JSON object with the bookmarked words
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                word:
                  type: string
                  description: The bookmarked word
      responses:
        "201":
          description: JSON object with the success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message of successful adding
        "401":
          description: JSON object with the error message due to unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
    put:                 
      summary: Update bookmarked words
      description: Update bookmarked words
      parameters:
        - name: userID
          in: path
          description: The user ID
          required: true
          schema:
            type: number
            example: 1
      requestBody:
        description: JSON object with the bookmarked words
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                originalWord:
                  type: string
                  description: The original word
                newWord:
                  type: string
                  description: The new word
      responses:
        "200":
          description: JSON object with the success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message of successful updating
        "401":
          description: JSON object with the error message due to unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
    delete:
      summary: Delete bookmarked word(s)
      description: Delete bookmarked word(s)
      parameters:
        - name: userID
          in: path
          description: The user ID
          required: true
          schema:
            type: number
            example: 1
        - name: all
          in: query
          description: Boolean indicating if all bookmarked words should be deleted
          required: false
          schema:
            type: boolean
            example: true
      requestBody:
        description: JSON object with the bookmarked words
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                word:
                  type: string
                  description: The bookmarked word
      responses:
        "200":
          description: JSON object with the success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message of successful deleting
        "401":
          description: JSON object with the error message due to unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /api-stats:
    get:
      summary: Get API usage statistics
      tags:
        - API Statistics
      description: Get the API usage statistics based on the JWT token in HttpOnly secure cookie
      responses:
        "200":
          description: JSON object with the API usage statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  usageStats:
                    type: array
                    items:
                      type: object
                      properties:
                        api-name:
                          type: string
                          description: The name of the API
                        request-type:
                          type: string
                          description: The type of the API request
                        count:
                          type: integer
                          description: The number of API calls
        "400":
          description: JSON object with the error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /users-info:
    get:
      summary: Get users info
      tags:
        - API Statistics
      description: Get username, email, role, and API usage statistics of all users
      responses:
        "200":
          description: JSON object with the users info
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
                      description: The username of the user
                    email:
                      type: string
                      description: The email of the user
                    role:
                      type: string
                      description: The role of the user
                    apiConsumption:
                      type: integer
                      description: The API consumption of the user
        "400":
          description: JSON object with the error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /api-consumption/{userID}:
    get:
      summary: Get API consumption
      tags:
        - API Statistics
      description: Get the API consumption of the current user
      parameters:
        - name: userID
          in: path
          description: The user userID
          required: true
          schema:
            type: number
            example: 1
      responses:
        "200":
          description: JSON object with the API consumption
          content:
            application/json:
              schema:
                type: object
                properties:
                  apiConsumption:
                    type: array
                    items:
                      type: object
                      properties:
                        api-name:
                          type: string
                          description: The name of the API
                        request-type:
                          type: string
                          description: The type of the API request
                        count:
                          type: integer
                          description: The number of API calls
        "400":
          description: JSON object with the error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  