openapi: 3.0.0
info:
  title: Example API
  description: This is an example API
  version: 1.0.0
servers:
  - url: http://localhost:8080/  # TODO: Make it dynamic
paths:
  /register:
    post:
      summary: Register
      description: Register a new user
      requestBody:
        description: JSON object with the user data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username
                password:
                  type: string
                  description: The password
      responses:
        "201":
          description: JSON object with the user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Message of successful registration
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /login:
    post:
      summary: Login
      description: Login a user
      requestBody:
        description: JSON object with the user data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: The username
                password:
                  type: string
                  description: The password
      responses:
        "200":
          description: JSON object with the user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: The generated JWT token for further authentication
        "401":
          description: JSON object with the error message due to unauthorized access
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        "500":
          description: JSON object with the error message due to internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message