openapi: 3.0.0
info:
  title: Example API
  description: This is an example API
  version: 1.0.0
servers:
  - url: http://localhost:8080/  # TODO: Make it dynamic
paths:
  /summarize-text:
    post:
      summary: Summarize text
      description: Summarize text
      requestBody:
        description: The text to summarize
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to summarize
      responses:
        "200":
          description: The summarized text
          content:
            application/json:
              schema:
                type: object
                properties:
                  text:
                    type: string
                    description: The summarized text