openapi: 3.0.0
info:
  title: Backend API for the News Summarizer
  description: This is the backend API for the News Summarizer
  version: 1.0.0
paths:
  /api-stats:
    get:
      summary: Get API usage statistics
      tags:
        - User
      description: Get the API usage statistics based on the JWT token in HttpOnly secure cookie
      responses:
        "200":
          description: JSON object with the API usage statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  usageStats:
                    type: array
                    items:
                      type: object
                      properties:
                        api-name:
                          type: string
                          description: The name of the API
                        request-type:
                          type: string
                          description: The type of the API request
                        count:
                          type: integer
                          description: The number of API calls
  /api-stats-by-user:
    get:
      summary: Get API usage statistics by user
      tags:
        - User
      description: Get the API usage statistics by user based on the JWT token in HttpOnly secure cookie
      responses:
        "200":
          description: JSON object with the API usage statistics by user
          content:
            application/json:
              schema:
                type: object
                properties:
                  usageStats:
                    type: array
                    items:
                      type: object
                      properties:
                        api-name:
                          type: string
                          description: The name of the API
                        request-type:
                          type: string
                          description: The type of the API request
                        count:
                          type: integer
                          description: The number of API calls
                        user:
                          type: string
                          description: The user's email
        "400":
          description: JSON object with the error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /api-consumption
    get:
      summary: Get API consumption
      tags:
        - User
      description: Get the API consumption of the current user
      responses:
        "200":
          description: JSON object with the API consumption
          content:
            application/json:
              schema:
                type: object
                properties:
                  apiConsumption:
                    type: array
                    items:
                      type: object
                      properties:
                        api-name:
                          type: string
                          description: The name of the API
                        request-type:
                          type: string
                          description: The type of the API request
                        count:
                          type: integer
                          description: The number of API calls
        "400":
          description: JSON object with the error message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /login:
    post:
      summary: Login user
      tags:
        - User
      description: Login with the given credentials
      requestBody:
        description: JSON object with the credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email
                password:
                  type: string
                  description: The user's password
      responses:
        "200":
          description: Successful login
          headers:
            Set-Cookie:
              description: The HttpOnly secure cookie with the token
              schema:
                type: string
                example: "token=123; HttpOnly; SameSite=Strict; Secure"
          content:
            application/json:
              schema:
                type: object
                properties:
                  role:
                    type: string
                    description: The user's role
                    example: "user"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /logout:
    post:
      summary: Logout user
      tags:
        - User
      description: Logout the user by clearing the HttpOnly secure cookie
      responses:
        "204":
          description: Successful logout
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /register:
    post:
      summary: Register user
      tags:
        - User
      description: Register with the given credentials
      requestBody:
        description: JSON object with the credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email
                password:
                  type: string
                  description: The user's password
      responses:
        "201":
          description: Successful registration
          headers:
            Set-Cookie:
              description: The HttpOnly secure cookie with the token
              schema:
                type: string
                example: "token=123; HttpOnly; SameSite=Strict; Secure"
          content:
            application/json:
              schema:
                type: object
                properties:
                  role:
                    type: string
                    description: The user's role
                    example: "user"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /summarize-text:
    post:
      summary: Summarize text
      tags:
        - Machine Learning
      description: Use the google/pegasus-large model on HuggingFace to summarize the given text
      requestBody:
        description: JSON object with the text to summarize
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to summarize
                  example: The federal suit, filed in Texas, comes on the heels of a Media Matters report that outlined how X — the platform formerly known as Twitter, which Musk now owns — placed . It also comes as Musk himself is on the platform. The Media Matters report from X, with Musk’s lawsuit marking just the latest controversy during his chaotic time steering one of the internet’s most prominent information platforms, . The report, published last week, pointed to ads from major companies who have long marketed themselves on the platform, including Apple, IBM and Oracle. The watchdog provided screenshots from searches on X and said it had also found advertisements from Amazon, NBA Mexico, NBCUniversal and others next to . After the Media Matters report was published, leading companies such as IBM and NBCUniversal — and its parent company, Comcast — said they once they learned their ads were appearing alongside material supporting Nazis. Other blue-chip companies, such as Apple, signaled a pause following Musk’s own rhetoric on X. Musk responded to the onslaught of criticism and advertiser boycotts by labeling the Media Matters report a “fraudulent attack” on his company and . Thank you for signing up! Subscribe to more newsletters Copyright 2023 Nexstar Media Inc. All rights reserved. This material may not be published, broadcast, rewritten, or redistributed.
      responses:
        "200":
          description: JSON object with the summarized text
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
                    description: The summarized text
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /news:
    get:
      summary: Get news
      tags:
        - News
      description: Get news from the news API
      parameters:
        - name: keyword
          in: query
          description: The keyword to search for
          required: true
          schema:
            type: string
          example: "javascript"
      responses:
        "200":
          description: JSON object with the news
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      description: The title of the article
                    link:
                      type: string
                      description: The link to the article
                    content:
                      type: string
                      description: The content of the article
                    published:
                      type: string
                      description: The date the article was published
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /role:
      get:
        summary: Get user role
        tags:
          - User
        description: Get the user role based on the JWT token in HttpOnly secure cookie
        responses:
          "200":
            description: JSON object with the user data
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    role:
                      type: string
                      description: The user's role
          "400":
            description: JSON object with the error message
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      description: The error message          
tags:
  - name: User
    description: API endpoints for user management
  - name: News
    description: API endpoints for news content
  - name: Machine Learning
    description: API endpoints for machine learning