openapi: 3.0.0
info:
  title: Example API
  description: This is an example API
  version: 1.0.0
servers:
  - url: http://localhost:8080/  # TODO: Make it dynamic
paths:
  # TODO: Update documentation
  /users:
    get:
      summary: Get a list of users
      description: Returns a list of users
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      description: The user's ID
                    name:
                      type: string
                      description: The user's name
    post:
      summary: Add a new user
      description: Adds a new user to the system
      requestBody:
        description: The user to add
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The user's name
      responses:
        "201":
          description: The newly created user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The user's ID
                  name:
                    type: string
                    description: The user's name
