openapi: 3.0.0
info:
  title: Example API
  description: This is an example API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Login user
      description: Login with the given credentials
      requestBody:
        description: JSON object with the credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email
                password:
                  type: string
                  description: The user's password
      responses:
        "204":
          description: No content
          headers:
            Set-Cookie:
              description: The HttpOnly secure cookie with the token
              schema:
                type: string
                example: "token=123; HttpOnly; SameSite=Strict; Secure"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /register:
    post:
      summary: Register user
      description: Register with the given credentials
      requestBody:
        description: JSON object with the credentials
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email
                password:
                  type: string
                  description: The user's password
      responses:
        "201":
          description: Confirmation of user registration success
          headers:
            Set-Cookie:
              description: The HttpOnly secure cookie with the token
              schema:
                type: string
                example: "token=123; HttpOnly; SameSite=Strict; Secure"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The success message
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /summarize-text:
    post:
      summary: Summarize text
      description: Use the google/pegasus-large model on HuggingFace to summarize the given text
      parameters:
        - name: Authorization  # TODO: Remove this after development is done
          in: header
          description: Token to authenticate the user
          schema:
            type: string
            example: "Bearer 123"
      requestBody:
        description: JSON object with the text to summarize
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to summarize
                  example: The federal suit, filed in Texas, comes on the heels of a Media Matters report that outlined how X — the platform formerly known as Twitter, which Musk now owns — placed . It also comes as Musk himself is on the platform. The Media Matters report from X, with Musk’s lawsuit marking just the latest controversy during his chaotic time steering one of the internet’s most prominent information platforms, . The report, published last week, pointed to ads from major companies who have long marketed themselves on the platform, including Apple, IBM and Oracle. The watchdog provided screenshots from searches on X and said it had also found advertisements from Amazon, NBA Mexico, NBCUniversal and others next to . After the Media Matters report was published, leading companies such as IBM and NBCUniversal — and its parent company, Comcast — said they once they learned their ads were appearing alongside material supporting Nazis. Other blue-chip companies, such as Apple, signaled a pause following Musk’s own rhetoric on X. Musk responded to the onslaught of criticism and advertiser boycotts by labeling the Media Matters report a “fraudulent attack” on his company and . Thank you for signing up! Subscribe to more newsletters Copyright 2023 Nexstar Media Inc. All rights reserved. This material may not be published, broadcast, rewritten, or redistributed.
      responses:
        "200":
          description: JSON object with the summarized text
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: string
                    description: The summarized text
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /news:
    get:
      summary: Get news
      description: Get news from the news API
      parameters:
        - name: keyword
          in: query
          description: The keyword to search for
          required: true
          schema:
            type: string
          example: "javascript"
        - name: Authorization  # TODO: Remove this after development is done
          in: header
          description: Token to authenticate the user
          schema:
            type: string
            example: "Bearer 123"
      responses:
        "200":
          description: JSON object with the news
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                      description: The title of the article
                    link:
                      type: string
                      description: The link to the article
                    content:
                      type: string
                      description: The content of the article
                    published:
                      type: string
                      description: The date the article was published
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: The error message
  /readAllFields/{tableName}:
    get:
      summary: Read all fields from the specified table
      description: Retrieve all fields from the specified table in the database
      parameters:
        - name: tableName
          in: path
          description: The name of the table
          required: true
          schema:
            type: string
      responses:
        "200":
          description: JSON object with all fields from the specified table
          content:
            application/json:
              schema:
                type: object
                # Adjust the schema based on the actual response format

  /createEntry/{tableName}:
    post:
      summary: Create an entry in the specified table
      description: Create a new entry in the specified table in the database
      parameters:
        - name: tableName
          in: path
          description: The name of the table
          required: true
          schema:
            type: string
      requestBody:
        description: JSON object with data for creating the entry
        required: true
        content:
          application/json:
            schema:
              type: object
              # Add the properties based on the data format for creating an entry

  /updateEntry/{tableName}/{entryId}:
    put:
      summary: Update an entry in the specified table
      description: Update an existing entry in the specified table in the database
      parameters:
        - name: tableName
          in: path
          description: The name of the table
          required: true
          schema:
            type: string
        - name: entryId
          in: path
          description: The ID of the entry to update
          required: true
          schema:
            type: integer
      requestBody:
        description: JSON object with data for updating the entry
        required: true
        content:
          application/json:
            schema:
              type: object
              # Add the properties based on the data format for updating an entry

  /deleteEntry/{tableName}/{entryId}:
    delete:
      summary: Delete an entry in the specified table
      description: Delete an entry from the specified table in the database
      parameters:
        - name: tableName
          in: path
          description: The name of the table
          required: true
          schema:
            type: string
        - name: entryId
          in: path
          description: The ID of the entry to delete
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Confirmation of entry deletion success
          content:
            application/json:
              schema:
                type: object
                # Add properties if needed for the success response
