AWSTemplateFormatVersion: '2010-09-09'

Transform: 'AWS::Serverless-2016-10-31'

Resources:
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: api.lambda_handler
      Runtime: python3.9
      Timeout: 120
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
      Policies:
        - AWSLambdaBasicExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 'sagemaker:InvokeEndpoint'
              Resource: !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/huggingface-pytorch-inference-2023-11-26-02-33-51-305"